"""FastAPI backend for the AI Stock Valuation Dashboard.

Reads financial data from raw_data.xlsx (generated by the main pipeline)
and serves it as JSON to the React frontend. Also provides an AI research
agent endpoint for generating valuation assumptions via Claude API.
"""
import os
from contextlib import asynccontextmanager
from pathlib import Path

from fastapi import FastAPI
from fastapi.responses import FileResponse
from fastapi.middleware.cors import CORSMiddleware
from fastapi.staticfiles import StaticFiles

from config import ALLOWED_ORIGINS, RAW_DATA_PATH, configured_providers, frontend_dist_available, FRONTEND_DIST_DIR
from routers import sheets, financials, analyze, pipeline, peers, critique


@asynccontextmanager
async def lifespan(app: FastAPI):
    """Startup / shutdown lifecycle handler (replaces deprecated on_event)."""
    # ── Startup ──────────────────────────────────────────────────────────────
    if not RAW_DATA_PATH.exists():
        print("=" * 70)
        print("[WARNING] raw_data.xlsx not found at:")
        print(f"  {RAW_DATA_PATH}")
        print("  Run 'py main.py' first to generate financial data.")
        print("=" * 70)
    else:
        print(f"[OK] raw_data.xlsx found at {RAW_DATA_PATH}")

    # Warn if CORS origins are still localhost-only in a non-local environment.
    # This catches the common mistake of forgetting to set the env var in production.
    origins_env = os.getenv("VALUATION_DASHBOARD_ALLOWED_ORIGINS", "")
    if not origins_env and os.getenv("FLY_APP_NAME"):
        # Running on Fly.io but no origins configured → cross-origin requests will fail
        print("=" * 70)
        print("[WARNING] VALUATION_DASHBOARD_ALLOWED_ORIGINS is not set.")
        print("  Cross-origin requests from Cloudflare Pages will be rejected.")
        print("  Set this env var to your Pages URL, e.g.:")
        print("  VALUATION_DASHBOARD_ALLOWED_ORIGINS=https://your-project.pages.dev")
        print("=" * 70)
    elif not origins_env:
        print("[INFO] CORS: localhost-only origins active (set VALUATION_DASHBOARD_ALLOWED_ORIGINS for production).")

    yield
    # ── Shutdown ─────────────────────────────────────────────────────────────
    # Nothing to clean up currently.


app = FastAPI(
    title="Valuation Dashboard API",
    version="1.0.0",
    lifespan=lifespan,
)

app.add_middleware(
    CORSMiddleware,
    allow_origins=ALLOWED_ORIGINS,
    allow_credentials=True,
    allow_methods=["GET", "POST"],
    allow_headers=["*"],
)

app.include_router(sheets.router, prefix="/api")
app.include_router(financials.router, prefix="/api")
app.include_router(analyze.router, prefix="/api")
app.include_router(pipeline.router, prefix="/api")
app.include_router(peers.router, prefix="/api")
app.include_router(critique.router, prefix="/api")

if frontend_dist_available():
    assets_dir = FRONTEND_DIST_DIR / "assets"
    if assets_dir.exists():
        app.mount("/assets", StaticFiles(directory=str(assets_dir)), name="dashboard-assets")


@app.get("/")
async def dashboard_index():
    index_path = FRONTEND_DIST_DIR / "index.html"
    if not index_path.exists():
        return {
            "status": "ok",
            "message": "Frontend assets not bundled. Start the Vite dev server or build the dashboard package.",
            "raw_data_exists": RAW_DATA_PATH.exists(),
        }
    return FileResponse(index_path)


@app.get("/api/health")
async def health_check() -> dict[str, object]:
    return {
        "status": "ok",
        "raw_data_exists": RAW_DATA_PATH.exists(),
        "configured_providers": configured_providers(),
        "configured_provider_count": len(configured_providers()),
    }


@app.get("/{full_path:path}")
async def dashboard_spa_fallback(full_path: str):
    if full_path.startswith("api/"):
        return {"status": "not_found"}

    requested_path = FRONTEND_DIST_DIR / Path(full_path)
    if requested_path.exists() and requested_path.is_file():
        return FileResponse(requested_path)

    index_path = FRONTEND_DIST_DIR / "index.html"
    if index_path.exists():
        return FileResponse(index_path)

    return {"status": "not_found"}
