/**
 * Excel export service — generates .xlsx matching Smit Financial Model structure.
 * Uses SheetJS (xlsx package) for client-side generation.
 *
 * Note: SheetJS community edition does not support cell styling (blue font).
 * Assumption cells are marked with [A] prefix to indicate hardcoded inputs.
 * For styled exports, upgrade to xlsx-style or ExcelJS.
 */
import * as XLSX from 'xlsx'
import type { ValuationRun } from '../types/ValuationRun.ts'
import type { FCFProjection } from '../types/DCFOutput.ts'
import type { SourcedAssumption } from '../types/Assumptions.ts'
import type { BlendedPriceTarget } from '../types/BlendedOutput.ts'
import type { ValuationConfig } from '../types/ValuationConfig.ts'
import { TerminalValueMethod, CashFlowBasis, DiscountingConvention } from '../types/ValuationConfig.ts'
import { format } from 'date-fns'

interface AssumptionExportRow {
  label: string
  value: string | number | boolean | null
  source: string
  confidence: string
  rationale: string
}

function addSheet(wb: XLSX.WorkBook, name: string, data: (string | number | null)[][], colWidths?: number[]): void {
  const ws = XLSX.utils.aoa_to_sheet(data)
  if (colWidths) {
    ws['!cols'] = colWidths.map(w => ({ wch: w }))
  }
  XLSX.utils.book_append_sheet(wb, ws, name)
}

function isSourcedAssumption(value: unknown): value is SourcedAssumption {
  return typeof value === 'object' && value !== null && 'value' in value && 'source' in value
}

function humanizeLabel(path: string): string {
  return path
    .replace(/\./g, ' ')
    .replace(/_/g, ' ')
    .replace(/\b\d+\b/g, match => `Y${Number(match) + 1}`)
    .replace(/\b\w/g, char => char.toUpperCase())
}

function collectAssumptionRows(label: string, value: unknown, rows: AssumptionExportRow[]): void {
  if (Array.isArray(value)) {
    value.forEach((item, index) => collectAssumptionRows(`${label}.${index}`, item, rows))
    return
  }

  if (isSourcedAssumption(value)) {
    rows.push({
      label: humanizeLabel(label),
      value: value.value,
      source: value.source,
      confidence: value.confidence,
      rationale: value.rationale,
    })
    return
  }

  if (typeof value === 'object' && value !== null) {
    Object.entries(value).forEach(([key, child]) => collectAssumptionRows(`${label}.${key}`, child, rows))
    return
  }

  rows.push({
    label: humanizeLabel(label),
    value: typeof value === 'string' || typeof value === 'number' || typeof value === 'boolean' ? value : null,
    source: 'System / User Input',
    confidence: '',
    rationale: '',
  })
}

function buildSourcesSheet(run: ValuationRun): (string | number | null)[][] {
  const rows: (string | number | null)[][] = []
  const assumptionRows: AssumptionExportRow[] = []

  if (run.assumptions) {
    collectAssumptionRows('wacc', run.assumptions.wacc, assumptionRows)
    collectAssumptionRows('dcf', run.assumptions.dcf, assumptionRows)
    collectAssumptionRows('ddm', run.assumptions.ddm, assumptionRows)
    collectAssumptionRows('comps', run.assumptions.comps, assumptionRows)
    collectAssumptionRows('scenarios', run.assumptions.scenarios, assumptionRows)
  }

  const confidenceSummary = assumptionRows.reduce(
    (summary, row) => {
      if (row.confidence === 'high') summary.high += 1
      if (row.confidence === 'medium') summary.medium += 1
      if (row.confidence === 'low') summary.low += 1
      return summary
    },
    { high: 0, medium: 0, low: 0 },
  )

  rows.push(['Sources & Methodology'])
  rows.push([])
  rows.push(['DATA SOURCES'])
  rows.push(['Financial data', 'raw_data.xlsx (OpenBB Platform + yfinance fallback)'])
  rows.push(['Economic data', 'Federal Reserve Economic Data (FRED)'])
  rows.push(['Industry benchmarks', 'Damodaran Online Datasets'])
  rows.push(['Assumptions', 'AI-generated by Claude / user overrides'])
  rows.push([])
  rows.push(['METHODOLOGY'])
  const cfg = run.valuationConfig
  const tvLabel = cfg?.dcfConfig.terminalValueMethod === TerminalValueMethod.ExitMultipleOnly ? 'Exit Multiple only'
    : cfg?.dcfConfig.terminalValueMethod === TerminalValueMethod.GordonGrowthOnly ? 'Gordon Growth only'
    : 'Dual terminal value (Gordon 40% + Exit Multiple 60%)'
  const cfLabel = cfg?.dcfConfig.cashFlowBasis === CashFlowBasis.FCFE ? 'FCFE (equity cash flow, discounted at ke)' : 'FCFF (unlevered, discounted at WACC)'
  const discLabel = cfg?.dcfConfig.discountingConvention === DiscountingConvention.MidPeriod ? 'Mid-year convention' : 'End-of-period'
  rows.push(['DCF', `5-year ${cfLabel} projection, ${tvLabel}, ${discLabel}`])
  rows.push(['DDM', 'Two-stage model when dividend history and payout criteria are met'])
  rows.push(['Comps', 'Peer median EV/EBITDA, P/E, EV/Sales, and P/B with configurable weights'])
  rows.push(['Scenarios', 'Bear/Base/Bull cases with probability-weighted expected value'])

  if (cfg) {
    rows.push([])
    rows.push(['VALUATION CONFIGURATION'])
    rows.push(['Terminal Value Method', tvLabel])
    rows.push(['Cash Flow Basis', cfLabel])
    rows.push(['Discounting Convention', discLabel])
    rows.push([])
    rows.push(['BLEND WEIGHTS'])
    rows.push(['DCF Sub-Weights', `Blended: ${Math.round(cfg.dcfSubWeights.blended * 100)}%, Exit: ${Math.round(cfg.dcfSubWeights.exitOnly * 100)}%, Gordon: ${Math.round(cfg.dcfSubWeights.gordonOnly * 100)}%`])
    rows.push(['Model Weights', `DCF: ${Math.round(cfg.modelWeights.dcf * 100)}%, Comps: ${Math.round(cfg.modelWeights.comps * 100)}%, DDM: ${Math.round(cfg.modelWeights.ddm * 100)}%`])
    if (run.blendedOutput?.finalPrice !== null && run.blendedOutput?.finalPrice !== undefined) {
      rows.push(['Final Price Target', run.blendedOutput.finalPrice])
    }
  }
  rows.push([])
  rows.push(['ASSUMPTION DETAIL'])
  rows.push(['Assumption', 'Value', 'Source', 'Confidence', 'Rationale'])
  assumptionRows.forEach(row => {
    rows.push([row.label, typeof row.value === 'boolean' ? (row.value ? 'True' : 'False') : row.value, row.source, row.confidence, row.rationale])
  })
  rows.push([])
  rows.push(['CONFIDENCE SUMMARY'])
  rows.push(['High', confidenceSummary.high])
  rows.push(['Medium', confidenceSummary.medium])
  rows.push(['Low', confidenceSummary.low])
  rows.push([])
  rows.push(['Analysis Date', format(new Date(run.createdAt), 'yyyy-MM-dd HH:mm')])
  rows.push(['Version', 'valuation-dashboard'])

  return rows
}

function buildFinancialStatementForecast(run: ValuationRun): (string | number | null)[][] {
  const rows: (string | number | null)[][] = []
  const projections = run.dcfOutput?.projections ?? []

  rows.push(['Financial Statement Forecast', '', '', '', '', '', ''])
  rows.push(['', 'Historical', '', '', 'Projected', '', '', '', ''])

  // Revenue history + projections
  const revenueHistory = run.financialData?.revenueHistory ?? []
  const headerRow: (string | number | null)[] = ['Metric']
  revenueHistory.forEach(h => headerRow.push(h.year))
  projections.forEach(p => headerRow.push(`Year ${p.year}`))
  rows.push(headerRow)

  const revenueRow: (string | number | null)[] = ['Revenue']
  revenueHistory.forEach(h => revenueRow.push(h.value))
  projections.forEach(p => revenueRow.push(p.revenue))
  rows.push(revenueRow)

  const growthRow: (string | number | null)[] = ['Revenue Growth [A]']
  revenueHistory.forEach(() => growthRow.push(null))
  projections.forEach(p => growthRow.push(p.revenueGrowth))
  rows.push(growthRow)

  const ebitdaRow: (string | number | null)[] = ['EBITDA']
  const ebitdaHistory = run.financialData?.ebitdaHistory ?? []
  ebitdaHistory.forEach(h => ebitdaRow.push(h.value))
  projections.forEach(p => ebitdaRow.push(p.ebitda))
  rows.push(ebitdaRow)

  const marginRow: (string | number | null)[] = ['EBITDA Margin [A]']
  ebitdaHistory.forEach(() => marginRow.push(null))
  projections.forEach(p => marginRow.push(p.ebitdaMargin))
  rows.push(marginRow)

  const capexRow: (string | number | null)[] = ['CapEx']
  revenueHistory.forEach(() => capexRow.push(null))
  projections.forEach(p => capexRow.push(-p.capex))
  rows.push(capexRow)

  const fcfRow: (string | number | null)[] = ['Free Cash Flow']
  revenueHistory.forEach(() => fcfRow.push(null))
  projections.forEach(p => fcfRow.push(p.freeCashFlow))
  rows.push(fcfRow)

  rows.push([])
  rows.push(['[A] = Hardcoded assumption (editable)'])

  return rows
}

function buildDCFSheet(run: ValuationRun): (string | number | null)[][] {
  const rows: (string | number | null)[][] = []
  const dcf = run.dcfOutput
  const wacc = run.assumptions?.wacc

  rows.push(['DCF Valuation Model'])
  rows.push([])

  // WACC Build-Up
  rows.push(['WACC Build-Up', 'Value', 'Source'])
  if (wacc) {
    rows.push(['Risk-Free Rate [A]', wacc.risk_free_rate.value, wacc.risk_free_rate.source])
    rows.push(['Equity Risk Premium [A]', wacc.equity_risk_premium.value, wacc.equity_risk_premium.source])
    rows.push(['Beta [A]', wacc.beta.value, wacc.beta.source])
    rows.push(['Size Premium [A]', wacc.size_premium.value, wacc.size_premium.source])
    rows.push(['Cost of Equity', dcf?.costOfEquity ?? null, 'Calculated: Rf + Beta*ERP + SP'])
    rows.push([])
    rows.push(['Cost of Debt [A]', wacc.cost_of_debt.value, wacc.cost_of_debt.source])
    rows.push(['Tax Rate [A]', wacc.tax_rate.value, wacc.tax_rate.source])
    rows.push(['After-Tax Cost of Debt', dcf?.afterTaxCostOfDebt ?? null, 'Calculated: Kd*(1-T)'])
    rows.push([])
    rows.push(['Debt Weight [A]', wacc.debt_weight.value, wacc.debt_weight.source])
    rows.push(['Equity Weight [A]', wacc.equity_weight.value, wacc.equity_weight.source])
    rows.push(['WACC', dcf?.wacc ?? null, 'Calculated: We*Ke + Wd*Kd*(1-T)'])
  }

  rows.push([])

  // FCF Projections
  if (dcf) {
    rows.push(['FCF Projections', 'Y1', 'Y2', 'Y3', 'Y4', 'Y5'])
    const metrics: [string, (p: FCFProjection) => number | null][] = [
      ['Revenue', p => p.revenue],
      ['Revenue Growth [A]', p => p.revenueGrowth],
      ['EBITDA', p => p.ebitda],
      ['Taxes', p => p.taxes],
      ['CapEx', p => -p.capex],
      ['NWC Change', p => -p.nwcChange],
      ['Free Cash Flow', p => p.freeCashFlow],
      ['Discount Factor', p => p.discountFactor],
      ['PV of FCF', p => p.pvFCF],
    ]
    for (const [label, getter] of metrics) {
      const row: (string | number | null)[] = [label]
      dcf.projections.forEach(p => row.push(getter(p)))
      rows.push(row)
    }

    rows.push([])
    rows.push(['Valuation Summary'])
    rows.push(['PV of FCFs', dcf.pvFCFTotal])
    rows.push(['Terminal Value (Gordon Growth)', dcf.terminalValueGordon])
    rows.push(['Terminal Value (Exit Multiple)', dcf.terminalValueExitMultiple])
    rows.push(['PV Terminal (Gordon)', dcf.pvTerminalGordon])
    rows.push(['PV Terminal (Exit Multiple)', dcf.pvTerminalExitMultiple])
    rows.push(['Enterprise Value (Gordon)', dcf.enterpriseValueGordon])
    rows.push(['Enterprise Value (Exit Multiple)', dcf.enterpriseValueExitMultiple])
    rows.push(['Net Debt', dcf.netDebt])
    rows.push(['Equity Value (Gordon)', dcf.equityValueGordon])
    rows.push(['Equity Value (Exit Multiple)', dcf.equityValueExitMultiple])
    rows.push(['Shares Outstanding', dcf.sharesOutstanding])
    rows.push(['Implied Price (Gordon)', dcf.impliedPriceGordon])
    rows.push(['Implied Price (Exit Multiple)', dcf.impliedPriceExitMultiple])
    rows.push(['Implied Price (Blended)', dcf.impliedPrice])

    // Sensitivity matrix
    rows.push([])
    rows.push(['Sensitivity: WACC vs Exit Multiple'])
    const sensHeader: (string | number | null)[] = ['WACC \\ Exit']
    dcf.sensitivityTerminalRange.forEach(t => sensHeader.push(`${t.toFixed(1)}x`))
    rows.push(sensHeader)
    dcf.sensitivityMatrix.forEach((matrixRow, i) => {
      const row: (string | number | null)[] = [`${(dcf.sensitivityWACCRange[i] * 100).toFixed(1)}%`]
      matrixRow.forEach(v => row.push(Math.round(v * 100) / 100))
      rows.push(row)
    })
  }

  rows.push([])
  rows.push(['[A] = Hardcoded assumption (editable input)'])

  return rows
}

function buildDDMSheet(run: ValuationRun): (string | number | null)[][] {
  const rows: (string | number | null)[][] = []
  const ddm = run.ddmOutput

  rows.push(['Dividend Discount Model'])
  rows.push([])

  rows.push(['Applicability Check', 'Result', 'Detail'])
  if (ddm) {
    ddm.applicabilityCriteria.forEach(c => {
      rows.push([c.name, c.pass ? 'PASS' : 'FAIL', c.detail])
    })
    rows.push(['Overall', ddm.isApplicable ? 'APPLICABLE' : 'NOT APPLICABLE', `Score: ${ddm.applicabilityScore}/4`])
  }

  if (ddm?.isApplicable) {
    rows.push([])
    rows.push(['DDM Inputs', 'Value'])
    rows.push(['Current DPS', ddm.currentDPS])
    rows.push(['Required Return (ke) [A]', ddm.requiredReturn])
    rows.push(['Short-Term Growth [A]', ddm.shortTermGrowth])
    rows.push(['Long-Term Growth [A]', ddm.longTermGrowth])
    rows.push([])
    rows.push(['Results'])
    rows.push(['Single-Stage Price', ddm.singleStagePrice])
    rows.push(['Two-Stage Price', ddm.twoStagePrice])
    rows.push(['Implied Price', ddm.impliedPrice])

    if (ddm.dpsProjections.length > 0) {
      rows.push([])
      rows.push(['DPS Projections', 'DPS', 'Growth', 'PV of DPS'])
      ddm.dpsProjections.forEach(p => {
        rows.push([`Year ${p.year}`, p.dps, p.growthRate, p.pvDPS])
      })
    }
  }

  return rows
}

function buildRelativeValuationSheet(run: ValuationRun): (string | number | null)[][] {
  const rows: (string | number | null)[][] = []
  const comps = run.compsOutput

  rows.push(['Relative Valuation (Comparable Company Analysis)'])
  rows.push([])

  if (comps) {
    rows.push(['Ticker', 'Company', 'EV/EBITDA', 'P/E', 'EV/Sales', 'P/B'])
    comps.peerTable.forEach(p => {
      rows.push([p.ticker, p.companyName, p.evToEbitda, p.pe, p.evToSales, p.pb])
    })
    rows.push(['MEDIAN', '', comps.medians.evToEbitda, comps.medians.pe, comps.medians.evToSales, comps.medians.pb])

    rows.push([])
    rows.push(['Implied Prices', 'Peer Median', 'Implied Price', 'Status'])
    comps.impliedPrices.forEach(ip => {
      rows.push([ip.multiple, ip.peerMedian, ip.impliedPrice, ip.isApplicable ? 'Applied' : ip.reason])
    })
    rows.push([])
    rows.push(['Weighted Implied Price', comps.weightedImpliedPrice])
  }

  return rows
}

function buildScenarioSheet(run: ValuationRun): (string | number | null)[][] {
  const rows: (string | number | null)[][] = []
  const scenario = run.scenarioOutput

  rows.push(['Scenario Analysis'])
  rows.push([])

  if (scenario) {
    const probabilityWeights = scenario.probabilityWeights ?? { bear: 0.25, base: 0.5, bull: 0.25 }

    rows.push(['Assumption Drivers', 'Bear', 'Base', 'Bull'])
    scenario.drivers.forEach(d => {
      rows.push([d.assumption, d.bearValue, d.baseValue, d.bullValue])
    })

    rows.push([])
    rows.push(['Probability Weights', probabilityWeights.bear, probabilityWeights.base, probabilityWeights.bull])

    rows.push([])
    rows.push(['Implied Prices', 'Bear', 'Base', 'Bull'])
    rows.push(['DCF', scenario.bear.dcfPrice, scenario.base.dcfPrice, scenario.bull.dcfPrice])
    rows.push(['DDM', scenario.bear.ddmPrice, scenario.base.ddmPrice, scenario.bull.ddmPrice])
    rows.push(['Comps', scenario.bear.compsPrice, scenario.base.compsPrice, scenario.bull.compsPrice])
    rows.push(['Weighted', scenario.bear.weightedPrice, scenario.base.weightedPrice, scenario.bull.weightedPrice])
    rows.push(['Expected Value (Probability-Weighted)', null, scenario.expectedPrice, null])
  }

  return rows
}

function buildAboutSheet(run: ValuationRun): (string | number | null)[][] {
  const rows: (string | number | null)[][] = []
  const data = run.financialData

  rows.push(['About Company'])
  rows.push([])
  rows.push(['Field', 'Value'])
  rows.push(['Ticker', run.ticker])
  rows.push(['Company Name', run.companyName])
  rows.push(['Sector', data?.sector ?? 'N/A'])
  rows.push(['Industry', data?.industry ?? 'N/A'])
  rows.push(['Current Price', run.currentPrice])
  rows.push(['Market Cap', data?.marketCap ?? null])
  rows.push(['Enterprise Value', data?.enterpriseValue ?? null])
  rows.push(['Beta', data?.beta ?? null])
  rows.push(['52-Week High', data?.fiftyTwoWeekHigh ?? null])
  rows.push(['52-Week Low', data?.fiftyTwoWeekLow ?? null])
  rows.push([])
  rows.push(['Analysis Date', format(new Date(run.createdAt), 'yyyy-MM-dd HH:mm')])
  rows.push([])

  if (run.assumptions?.investment_thesis) {
    rows.push(['Investment Thesis'])
    rows.push([run.assumptions.investment_thesis])
  }

  if (run.assumptions?.key_risks && run.assumptions.key_risks.length > 0) {
    rows.push([])
    rows.push(['Key Risks'])
    run.assumptions.key_risks.forEach(risk => rows.push([risk]))
  }

  rows.push([])
  rows.push(['Generated by', 'AI Stock Valuation Dashboard'])
  rows.push(['Note', '[A] markers indicate hardcoded assumptions (editable inputs)'])

  return rows
}

function buildBlendedValuationSheet(run: ValuationRun): (string | number | null)[][] {
  const rows: (string | number | null)[][] = []
  const blend = run.blendedOutput
  const cfg = run.valuationConfig

  rows.push(['Blended Valuation'])
  rows.push([])

  if (blend && cfg) {
    rows.push(['Component', 'Implied Price', 'Weight', 'Contribution'])
    rows.push([])
    rows.push(['DCF Sub-Components'])
    const dcfComponents: Array<{ label: string; price: number | null; weightKey: string }> = [
      { label: 'DCF (Blended 40/60)', price: blend.dcfBlendedPrice, weightKey: 'blended' },
      { label: 'DCF (Exit Multiple)', price: blend.dcfExitOnlyPrice, weightKey: 'exitOnly' },
      { label: 'DCF (Gordon Growth)', price: blend.dcfGordonOnlyPrice, weightKey: 'gordonOnly' },
    ]
    for (const comp of dcfComponents) {
      const w = blend.effectiveDCFSubWeights[comp.weightKey as keyof typeof blend.effectiveDCFSubWeights]
      const contribution = comp.price !== null ? comp.price * w : null
      rows.push([comp.label, comp.price, w, contribution])
    }
    rows.push(['Combined DCF', blend.combinedDCFPrice, null, null])

    rows.push([])
    rows.push(['Model Blend'])
    const modelComponents: Array<{ label: string; price: number | null; weightKey: string }> = [
      { label: 'DCF', price: blend.combinedDCFPrice, weightKey: 'dcf' },
      { label: 'Comps', price: blend.compsPrice, weightKey: 'comps' },
      { label: 'DDM', price: blend.ddmPrice, weightKey: 'ddm' },
    ]
    for (const comp of modelComponents) {
      const w = blend.effectiveModelWeights[comp.weightKey as keyof typeof blend.effectiveModelWeights]
      const contribution = comp.price !== null ? comp.price * w : null
      rows.push([comp.label, comp.price, w, contribution])
    }
    rows.push([])
    rows.push(['FINAL PRICE TARGET', blend.finalPrice, 1.0, blend.finalPrice])
  } else {
    rows.push(['Blended valuation not available'])
  }

  return rows
}

export function exportToExcel(run: ValuationRun): void {
  const wb = XLSX.utils.book_new()

  addSheet(wb, 'Financial Statement Forecast', buildFinancialStatementForecast(run), [25, 18, 18, 18, 18, 18, 18, 18, 18])
  addSheet(wb, 'DCF', buildDCFSheet(run), [30, 18, 18, 18, 18, 18])
  addSheet(wb, 'DDM', buildDDMSheet(run), [30, 18, 18, 18])
  addSheet(wb, 'Relative Valuation', buildRelativeValuationSheet(run), [12, 25, 12, 12, 12, 12])
  addSheet(wb, 'Blended Valuation', buildBlendedValuationSheet(run), [22, 18, 12, 18])
  addSheet(wb, 'Scenario Analysis', buildScenarioSheet(run), [25, 18, 18, 18])
  addSheet(wb, 'About_Company', buildAboutSheet(run), [25, 50])
  addSheet(wb, 'Sources_Methodology', buildSourcesSheet(run), [30, 18, 24, 14, 50])

  const dateStr = format(new Date(run.createdAt), 'yyyyMMdd')
  const filename = `${run.ticker}_Valuation_${dateStr}.xlsx`

  XLSX.writeFile(wb, filename)
}
