"""Pydantic models for valuation assumptions generated by the AI agent.

These models mirror the frontend TypeScript types exactly.
"""
from __future__ import annotations

from pydantic import BaseModel, Field


class SourcedAssumption(BaseModel):
    value: float
    source: str = Field(description="Citation, e.g. '10-K FY2024 p.42'")
    confidence: str = Field(description="high | medium | low", default="medium")
    rationale: str = Field(max_length=300, default="")


class DCFAssumptions(BaseModel):
    revenue_growth_rates: list[SourcedAssumption] = Field(
        description="5 years of projected revenue growth rates (decimal, e.g. 0.08 = 8%)"
    )
    ebitda_margin: SourcedAssumption = Field(
        description="Stabilized EBITDA margin (decimal)"
    )
    capex_pct_revenue: SourcedAssumption = Field(
        description="CapEx as % of revenue (decimal)"
    )
    nwc_pct_revenue: SourcedAssumption = Field(
        description="Net working capital change as % of revenue (decimal)"
    )
    tax_rate: SourcedAssumption = Field(
        description="Effective tax rate (decimal)"
    )
    terminal_growth_rate: SourcedAssumption = Field(
        description="Long-term growth rate for Gordon Growth (decimal)"
    )
    exit_multiple: SourcedAssumption = Field(
        description="EV/EBITDA exit multiple"
    )


class WACCAssumptions(BaseModel):
    risk_free_rate: SourcedAssumption
    equity_risk_premium: SourcedAssumption
    beta: SourcedAssumption
    size_premium: SourcedAssumption
    cost_of_debt: SourcedAssumption
    debt_weight: SourcedAssumption
    equity_weight: SourcedAssumption
    tax_rate: SourcedAssumption


class DDMAssumptions(BaseModel):
    is_applicable: bool = Field(
        description="Whether DDM is valid for this company"
    )
    applicability_reason: str = ""
    short_term_growth_rate: SourcedAssumption | None = None
    long_term_growth_rate: SourcedAssumption | None = None
    required_return: SourcedAssumption | None = None
    high_growth_years: int = Field(default=5, description="Years of high growth in two-stage model")


class CompsAssumptions(BaseModel):
    selected_peers: list[str] = Field(
        description="4-6 comparable company tickers"
    )
    peer_selection_rationale: str = ""
    primary_multiple: str = Field(
        default="EV/EBITDA",
        description="EV/EBITDA or P/E -- whichever is more appropriate"
    )
    multiple_rationale: str = ""


class ScenarioDrivers(BaseModel):
    bear: SourcedAssumption = Field(description="Bear case value")
    base: SourcedAssumption = Field(description="Base case value")
    bull: SourcedAssumption = Field(description="Bull case value")


class ScenarioAssumptions(BaseModel):
    revenue_growth: ScenarioDrivers
    ebitda_margin: ScenarioDrivers
    exit_multiple: ScenarioDrivers
    wacc: ScenarioDrivers


class ForecastItem(BaseModel):
    year: int
    value: float
    confidence: str = Field(description="high | medium | low", default="medium")
    rationale: str = Field(max_length=500, default="")


class AccountOverride(BaseModel):
    account: str
    new_value: float
    rationale: str = Field(max_length=300, default="")


class ForecastAssumptions(BaseModel):
    revenue_forecasts: list[ForecastItem] = Field(default_factory=list)
    ebit_margins: list[ForecastItem] = Field(default_factory=list)
    ebitda_margins: list[ForecastItem] = Field(default_factory=list)
    effective_tax_rate: float = 0.21
    account_overrides: list[AccountOverride] = Field(default_factory=list)
    revenue_thesis: str = ""
    margin_thesis: str = ""
    key_assumptions: list[str] = Field(default_factory=list)


class Assumptions(BaseModel):
    dcf: DCFAssumptions
    wacc: WACCAssumptions
    ddm: DDMAssumptions
    comps: CompsAssumptions
    scenarios: ScenarioAssumptions
    forecast: ForecastAssumptions = Field(default_factory=ForecastAssumptions)
    investment_thesis: str = Field(
        max_length=500,
        default="",
        description="One-paragraph investment thesis"
    )
    key_risks: list[str] = Field(
        default_factory=list,
        description="Top 3-5 risk factors"
    )
